### ISSUE TITLE
unable to compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by rpgrimm** [open-power/eCMD#3]
I created a makefile for Ubuntu 16.04.  See https://github.com/rpgrimm/eCMD/commit/086075e2991cb79f74f88a6ef9f4244f9b9edac5

Things seem OK until I hit this:

eCMD Python Module x86_64 ...
***** If you see python load errors this build of the python module is invalid ****
Traceback (most recent call last):
  File "../pyapi/testBuild.py", line 2, in <module>
    import ecmd
  File "/home/rgrimm/trees/ecmd-rgrimm/out_x86_64/pyapi/ecmd.py", line 3417, in <module>
    def ecmdLooperInit(io_target, i_looptype, io_state, i_mode=ECMD_DYNAMIC_LOOP):
NameError: name 'ECMD_DYNAMIC_LOOP' is not defined
makefile:85: recipe for target 'test' failed
make[2]: *** [test] Error 1
makefile:126: recipe for target 'ecmdpyapi' failed
make[1]: *** [ecmdpyapi] Error 2
makefile:63: recipe for target 'all' failed
make: *** [all] Error 2

Any Idea on how to fix?  I attached the whole build output if it helps.
[ecmd-compile.txt](https://github.com/open-power/eCMD/files/389753/ecmd-compile.txt)

**Comment by mklight** [comment]
Thanks for reporting the issue.
@thejta has fixed this in our internal git repo, it is due to the .i ordering. I will work on pulling the updates into github by tomorrow.

**Comment by mklight** [comment]
I have updated the master branch with the latest from the internal repo. Please try it out. Thanks.

**Comment by rpgrimm** [comment]
Thanks, I can compile now with the master branch.
