### ISSUE TITLE
pyecmd doesn't build on RHEL6

### ISSUE THREAD

**Issue by thejta** [open-power/eCMD#78]
When building on RHEL6, I get this error:

```
pyeCMD Module x86_64 ...
***** If you see python load errors this build of the python module is invalid ****
Traceback (most recent call last):
  File "test_api.py", line 1, in <module>
    from pyecmd import *
  File "/home/albertj/ecmd/out_x86_64/pyecmd/__init__.py", line 96, in <module>
    from .generated import *
  File "/home/albertj/ecmd/out_x86_64/pyecmd/generated.py", line 20
    def &nbsp;ecmdParseOptionWithArgs(io_argv, i_option):
        ^
SyntaxError: invalid syntax
make[2]: *** [test] Error 1
make[1]: *** [pyecmd] Error 2
make: *** [all] Error 2
```

After some testing, it looks to be a problem with the default doxygen that comes with RHEL6 (1.6.1)

If I install the latest doxygen (1.8.14) and build, that error goes away.  Hopefully there is a solution that will allow the OS default to be used.

**Comment by thejta** [comment]
I couldn't assign this to @fenkes-ibm - not sure what that is, so tagging him in a comment here.

**Comment by fenkes-ibm** [comment]
Maybe I need to become part of the project team before you can assign this to me -- but I'll take a look!

**Comment by fenkes-ibm** [comment]
Yep, it was a missing entity replacement in generate-pyecmd.py. I created pull request #79 to fix that.

**Comment by fenkes-ibm** [comment]
I accidentally the pull request. Created #80 in its stead and fixed the new build problem @thejta was getting.

**Comment by mklight** [comment]
closing as reported fixed by @thejta
